### ISSUE TITLE
Quartus NIOS console out not working

### ISSUE THREAD

**Issue by Wiljan1** [tow3rs/jtag-mpsse-blaster#2]
On Win10 Quartus 17.1 Std and Catapult 2 PCI board X930613-001 with FT232H onboard

A "Hello World" NIOSII project the STDOUT print does not show up in Eclipse
The program does run fine in NIOS (have some led counting)

If I use an old clone USB Blaster on the JTGA connector on the board the NIOS console print out the "Hello World" fine with the same code.

I did add a logic analyser on the JTAG and it's clear the after loading the program to the FPGA the USB Blaster clone does have a kind of polling running to show the STDOUT promt, when the mpsse blaster have no communication after loading the code.

If I use debug in Eclipse it does fine read the variables in the FPGA NIOS so it's possible to read back data

So I guess something are missing in the mpsse code?

**Comment by tow3rs** [comment]
@Wiljan1, believe it or not, this problem was caused by the port name itself, so after removing the VID and PID from the port name: `[00 Single RS232-HS (0403:6014)]` to `[00 Single RS232-HS]` -> voilà! the NIOS console has started working.
It`s fixed in version 1.0.2.

**Comment by Wiljan1** [comment]
@tow3rs , crazy reason, but I can confirm that the NIOS console does work fine in v1.02 so issue can be closed.

`Hello from Nios II!
Count: 0
Count: 1
Count: 2
Count: 3
Count: 4
Count: 5
Count: 6
Count: 7
Count: 8
Count: 9
Count: 10
Count: 11
`
Thank you for fixing it
